### PR TITLE
Multi-GPU Temp detection and support

### PR DESCRIPTION
**Pull request by DominicTWHV**
Added support in nvidia-smi for multi-GPU support

Tested on my own system (R720 with dual P100s)

### CODE REVIEW

**Comment by DominicTWHV** [comment]
Pulling the highest temperature from all detected GPUs and setting that as $GPU_TEMP

**Comment by DominicTWHV** [comment]
Offset fan speeds to prevent extreme overheating.

**Comment by DominicTWHV** [comment]
Added more fan settings and thermal runaway shutdown at 100c (or above)

**Comment by Olaren15** [comment]
Hey Dominic,

Thanks for the PR. I would be happy to accept the feature that adds support for multiple GPUs.
However, I would rather not change the temperature thresholds and actions associated with them since that part would be different for every system/configuration. With that said, I think I should specify in the README that users of this script should experiment and edit those values to fit their use case :)

**Comment by DominicTWHV** [comment]
Will make an update to the temp logic later on, for now I'll revert the temp changes. A new PR would be opened soon when I get to it

**Review by DominicTWHV — COMMENTED** [review]
Confirmed to function as intended.

**Comment by DominicTWHV** [comment]
@Olaren15 Ready for merging?

**Review by Olaren15 — APPROVED** [review]

**Comment by Olaren15** [comment]
I'm so sorry for the delay, I completely forgot about this PR. Thanks again for the contribution :)

**Pull request merged**
